/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerDashboardRouteImport } from './routes/volunteer-dashboard'
import { Route as ResponderDashboardRouteImport } from './routes/responder-dashboard'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HospitalDashboardRouteImport } from './routes/hospital-dashboard'
import { Route as CitizenDashboardRouteImport } from './routes/citizen-dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVolunteersRouteImport } from './routes/app.volunteers'
import { Route as AppSmsGatewayRouteImport } from './routes/app.sms-gateway'
import { Route as AppSafeCheckinRouteImport } from './routes/app.safe-checkin'
import { Route as AppReunificationRouteImport } from './routes/app.reunification'
import { Route as AppResourcesRouteImport } from './routes/app.resources'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppIncidentsRouteImport } from './routes/app.incidents'
import { Route as AppHospitalRouteImport } from './routes/app.hospital'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAiOpsRouteImport } from './routes/app.ai-ops'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'

const VolunteerDashboardRoute = VolunteerDashboardRouteImport.update({
  id: '/volunteer-dashboard',
  path: '/volunteer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponderDashboardRoute = ResponderDashboardRouteImport.update({
  id: '/responder-dashboard',
  path: '/responder-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDashboardRoute = HospitalDashboardRouteImport.update({
  id: '/hospital-dashboard',
  path: '/hospital-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenDashboardRoute = CitizenDashboardRouteImport.update({
  id: '/citizen-dashboard',
  path: '/citizen-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVolunteersRoute = AppVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AppRoute,
} as any)
const AppSmsGatewayRoute = AppSmsGatewayRouteImport.update({
  id: '/sms-gateway',
  path: '/sms-gateway',
  getParentRoute: () => AppRoute,
} as any)
const AppSafeCheckinRoute = AppSafeCheckinRouteImport.update({
  id: '/safe-checkin',
  path: '/safe-checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppReunificationRoute = AppReunificationRouteImport.update({
  id: '/reunification',
  path: '/reunification',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppIncidentsRoute = AppIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalRoute = AppHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiOpsRoute = AppAiOpsRouteImport.update({
  id: '/ai-ops',
  path: '/ai-ops',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/app': typeof AppRouteWithChildren
  '/citizen-dashboard': typeof CitizenDashboardRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/responder-dashboard': typeof ResponderDashboardRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-ops': typeof AppAiOpsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/hospital': typeof AppHospitalRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/map': typeof AppMapRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/reunification': typeof AppReunificationRoute
  '/app/safe-checkin': typeof AppSafeCheckinRoute
  '/app/sms-gateway': typeof AppSmsGatewayRoute
  '/app/volunteers': typeof AppVolunteersRoute
  '/app/': typeof AppIndexRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/citizen-dashboard': typeof CitizenDashboardRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/responder-dashboard': typeof ResponderDashboardRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-ops': typeof AppAiOpsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/hospital': typeof AppHospitalRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/map': typeof AppMapRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/reunification': typeof AppReunificationRoute
  '/app/safe-checkin': typeof AppSafeCheckinRoute
  '/app/sms-gateway': typeof AppSmsGatewayRoute
  '/app/volunteers': typeof AppVolunteersRoute
  '/app': typeof AppIndexRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/app': typeof AppRouteWithChildren
  '/citizen-dashboard': typeof CitizenDashboardRoute
  '/hospital-dashboard': typeof HospitalDashboardRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/responder-dashboard': typeof ResponderDashboardRoute
  '/volunteer-dashboard': typeof VolunteerDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AppAdminRoute
  '/app/ai-ops': typeof AppAiOpsRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/hospital': typeof AppHospitalRoute
  '/app/incidents': typeof AppIncidentsRoute
  '/app/map': typeof AppMapRoute
  '/app/resources': typeof AppResourcesRoute
  '/app/reunification': typeof AppReunificationRoute
  '/app/safe-checkin': typeof AppSafeCheckinRoute
  '/app/sms-gateway': typeof AppSmsGatewayRoute
  '/app/volunteers': typeof AppVolunteersRoute
  '/app/': typeof AppIndexRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/app'
    | '/citizen-dashboard'
    | '/hospital-dashboard'
    | '/login'
    | '/report'
    | '/responder-dashboard'
    | '/volunteer-dashboard'
    | '/api/chat'
    | '/app/admin'
    | '/app/ai-ops'
    | '/app/analytics'
    | '/app/hospital'
    | '/app/incidents'
    | '/app/map'
    | '/app/resources'
    | '/app/reunification'
    | '/app/safe-checkin'
    | '/app/sms-gateway'
    | '/app/volunteers'
    | '/app/'
    | '/api/public/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/citizen-dashboard'
    | '/hospital-dashboard'
    | '/login'
    | '/report'
    | '/responder-dashboard'
    | '/volunteer-dashboard'
    | '/api/chat'
    | '/app/admin'
    | '/app/ai-ops'
    | '/app/analytics'
    | '/app/hospital'
    | '/app/incidents'
    | '/app/map'
    | '/app/resources'
    | '/app/reunification'
    | '/app/safe-checkin'
    | '/app/sms-gateway'
    | '/app/volunteers'
    | '/app'
    | '/api/public/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/app'
    | '/citizen-dashboard'
    | '/hospital-dashboard'
    | '/login'
    | '/report'
    | '/responder-dashboard'
    | '/volunteer-dashboard'
    | '/api/chat'
    | '/app/admin'
    | '/app/ai-ops'
    | '/app/analytics'
    | '/app/hospital'
    | '/app/incidents'
    | '/app/map'
    | '/app/resources'
    | '/app/reunification'
    | '/app/safe-checkin'
    | '/app/sms-gateway'
    | '/app/volunteers'
    | '/app/'
    | '/api/public/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AppRoute: typeof AppRouteWithChildren
  CitizenDashboardRoute: typeof CitizenDashboardRoute
  HospitalDashboardRoute: typeof HospitalDashboardRoute
  LoginRoute: typeof LoginRoute
  ReportRoute: typeof ReportRoute
  ResponderDashboardRoute: typeof ResponderDashboardRoute
  VolunteerDashboardRoute: typeof VolunteerDashboardRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer-dashboard': {
      id: '/volunteer-dashboard'
      path: '/volunteer-dashboard'
      fullPath: '/volunteer-dashboard'
      preLoaderRoute: typeof VolunteerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responder-dashboard': {
      id: '/responder-dashboard'
      path: '/responder-dashboard'
      fullPath: '/responder-dashboard'
      preLoaderRoute: typeof ResponderDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-dashboard': {
      id: '/hospital-dashboard'
      path: '/hospital-dashboard'
      fullPath: '/hospital-dashboard'
      preLoaderRoute: typeof HospitalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen-dashboard': {
      id: '/citizen-dashboard'
      path: '/citizen-dashboard'
      fullPath: '/citizen-dashboard'
      preLoaderRoute: typeof CitizenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/volunteers': {
      id: '/app/volunteers'
      path: '/volunteers'
      fullPath: '/app/volunteers'
      preLoaderRoute: typeof AppVolunteersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sms-gateway': {
      id: '/app/sms-gateway'
      path: '/sms-gateway'
      fullPath: '/app/sms-gateway'
      preLoaderRoute: typeof AppSmsGatewayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safe-checkin': {
      id: '/app/safe-checkin'
      path: '/safe-checkin'
      fullPath: '/app/safe-checkin'
      preLoaderRoute: typeof AppSafeCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reunification': {
      id: '/app/reunification'
      path: '/reunification'
      fullPath: '/app/reunification'
      preLoaderRoute: typeof AppReunificationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resources': {
      id: '/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/incidents': {
      id: '/app/incidents'
      path: '/incidents'
      fullPath: '/app/incidents'
      preLoaderRoute: typeof AppIncidentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hospital': {
      id: '/app/hospital'
      path: '/hospital'
      fullPath: '/app/hospital'
      preLoaderRoute: typeof AppHospitalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-ops': {
      id: '/app/ai-ops'
      path: '/ai-ops'
      fullPath: '/app/ai-ops'
      preLoaderRoute: typeof AppAiOpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiOpsRoute: typeof AppAiOpsRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppHospitalRoute: typeof AppHospitalRoute
  AppIncidentsRoute: typeof AppIncidentsRoute
  AppMapRoute: typeof AppMapRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppReunificationRoute: typeof AppReunificationRoute
  AppSafeCheckinRoute: typeof AppSafeCheckinRoute
  AppSmsGatewayRoute: typeof AppSmsGatewayRoute
  AppVolunteersRoute: typeof AppVolunteersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiOpsRoute: AppAiOpsRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppHospitalRoute: AppHospitalRoute,
  AppIncidentsRoute: AppIncidentsRoute,
  AppMapRoute: AppMapRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppReunificationRoute: AppReunificationRoute,
  AppSafeCheckinRoute: AppSafeCheckinRoute,
  AppSmsGatewayRoute: AppSmsGatewayRoute,
  AppVolunteersRoute: AppVolunteersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AppRoute: AppRouteWithChildren,
  CitizenDashboardRoute: CitizenDashboardRoute,
  HospitalDashboardRoute: HospitalDashboardRoute,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
  ResponderDashboardRoute: ResponderDashboardRoute,
  VolunteerDashboardRoute: VolunteerDashboardRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
